
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Todo": "../../app",
  "Ext": "../../ext/src",
  "Todo.Application": "../../app/application.js",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Todo.store.Tasks": [],
  "Todo.controller.History": [],
  "Todo.view.List": [],
  "Todo.controller.BottomBar": [],
  "Todo.controller.List": [],
  "Todo.controller.TopBar": [],
  "Todo.model.Task": [],
  "Todo.view.TopBar": [],
  "Todo.Application": [],
  "Todo.view.BottomBar": [],
  "Todo.view.Viewport": []
});
Ext.ClassManager.addNameAliasMappings({
  "Todo.store.Tasks": [],
  "Todo.controller.History": [],
  "Todo.view.List": [
    "widget.todo_list"
  ],
  "Todo.controller.BottomBar": [],
  "Todo.controller.List": [],
  "Todo.controller.TopBar": [],
  "Todo.model.Task": [],
  "Todo.view.TopBar": [
    "widget.todo_topbar"
  ],
  "Todo.Application": [],
  "Todo.view.BottomBar": [
    "widget.todo_bottombar"
  ],
  "Todo.view.Viewport": []
});
